### PR TITLE
updates

### PR DESCRIPTION
**Pull request by titoBouzout**
Hi there, some updates, 

1. add Unicode Unescape
2. makes the context menu optional (offering as a template, instead of adding it directly which is hard to imposible to remove)

Looks like the whitespaces changed, you may want to look into the non-whitespace diff version here  https://github.com/dangelov/hasher/pull/13/files?w=1

### CODE REVIEW

**Comment by dangelov** [comment]
I have a few questions about the context menu:
1) How do you enable it? By renaming the file to remove "-template"?
2) If "yes" to the above, what happens if there's an update to Hasher? Would people have to replace their old context menu file with the new one?
3) Do the docs need to be updated to explain the context menu?

The Unicode Unescape looks good, I'm just a bit unclear on the above regarding the context menu.

**Comment by titoBouzout** [comment]
1. yes
2. no, their context menu of hasher will disappear, if they want to add the context menu they can use that template, they can just paste it in User/Context.sublime-menu
3. Yes Im agree

**Comment by ohaucke** [comment]
I'm not shure why the context menu disturbs? It is only one entry with a sub-menu.
I think this isn't the right way to do so, maybe it is possible to add an option to the user settings (Preferences.sublime-settings) whether the context menu is shown or not.

FYI: Not the whitespaces changed, you changed the linebreaks from \r\n to \n

**Comment by titoBouzout** [comment]
> I'm not shure why the context menu disturbs? 

Because I dont want it? For example, it puts "hasher" before "Cut". If I want to use hasher I can use it from the command palette, or if I want to have a context menu, I can add it my self, but if we add the context menu, theres no way to remove it, only possible by removing the file, which means we should edit the package. 

> maybe it is possible to add an option to the user settings (Preferences.sublime-settings) whether the context menu is shown or not.

You should not mix ST settings with a package setting.

**Comment by dangelov** [comment]
> only possible by removing the file, which means we should edit the package.
Isn't it similar right now? You have to edit the package to rename the file, so you get the menu. To be honest, I'm not sold on it's utility or ease of use. I'm inclined to skip including it, unless there's an easier way to toggle it.

Thoughts?

**Comment by titoBouzout** [comment]
No, is not the same thing to force everyone to have a menu in their context menu than to tell "Hey if you wish to add hasher to your context menu copy this file to User/Context.sublime-menu"

**Comment by ohaucke** [comment]
> You should not mix ST settings with a package setting. 
Sorry my fault, you are right package settings are recommend
-
You can use "Ctrl+x" for cut, but i understand your argument. With your suggestion you would force everyone who wants the menu to rename a file - which isn't better than remove a file (to remove the menu).

**Comment by titoBouzout** [comment]
You should not add thing by default that has no clear use. If users want these things they should add these by themselves. I think you don't understand the issue. 

If someone wants the menu, they add it, you don't add it to everyone. 

Adding the menu requires no hacks, but removing it requires editing a package. There is no need to edit the package to add the menu.

**Comment by titoBouzout** [comment]
I added the instructions to the readme and removed the file, please merge. Thanks

**Comment by dangelov** [comment]
After re-reading our discussion, I'm inclined to agree with you @titoBouzout. Merging now.

**Pull request merged**
