### PR TITLE
Addition to imported modules to allow NTLM to function

### PR DESCRIPTION
**Pull request by alphaskade**
Correction made.

### CODE REVIEW

**Comment by dangelov** [comment]
Thanks for the quick correction. Do you know if this import is ST2-compatible?

**Comment by dangelov** [comment]
Actually, I just downloaded ST2 and that function throws the following error:
```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./hasher.py", line 101, in run
IndexError: list index out of range
```
on a piece of random text.

**Comment by alphaskade** [comment]
Recreated. Will resolve as soon as possible.

**Comment by alphaskade** [comment]
Python 2.6.5 runs in the latest version of ST2 (that I can see from sys.version). ST3 runs Python 3. The output from hashlib's digest() method changed between the versions, resulting in a byte object in one version and a string in the other. 

https://docs.python.org/2/library/hashlib.html vs. https://docs.python.org/3/library/hashlib.html

Will probably use a quick if/elif to check the length of the list coming out of the string split to resolve.

**Comment by alphaskade** [comment]
Found a better way. Checked type and altered behaviour dependent on that.

**Comment by dangelov** [comment]
Tested in ST 2 & 3, worked nicely. Thanks, merged.

**Pull request merged**
